# Generated by Django 6.1.1 on 2026-09-16 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorias', models.CharField(choices=[('000', 'Generalidades e Informação: Obras gerais, enciclopédias, jornais e biblioteconomia.'), ('100', 'Filosofia e Psicologia: Ética, lógica e investigações sobre a mente humana.'), ('200', 'Religião e Teologia: Mitologia, teologia e estudos sobre crenças e religiões.'), ('300', 'Ciências Sociais e Direito: Política, economia, sociologia, educação e leis.'), ('400', 'Linguística e Idiomas: Gramáticas, dicionários e estudos de línguas.'), ('500', 'Ciências Puras (Exatas e Naturais): Matemática, física, química, biologia e astronomia.'), ('600', 'Ciências Aplicadas (Tecnologia): Medicina, engenharia, agricultura e administração.'), ('700', 'Artes e Recreação: Pintura, música, arquitetura, esportes e lazer.'), ('800', 'Literatura: Poesia, romances, contos, crônicas e crítica literária.'), ('900', ' História e Geografia: Biografias, viagens e acontecimentos históricos')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('digital', 'Livro digital'), ('fisico', 'Livro fisico')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=200)),
                ('ano', models.IntegerField()),
                ('disponivel', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acervo.categoria')),
                ('tipo', models.ForeignKey(default='digital', on_delete=django.db.models.deletion.CASCADE, to='acervo.tipo')),
            ],
        ),
    ]
